# Generated by Django 5.2.17 on 2026-10-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('personal', '개인'), ('corporate', '법인')], default='personal', max_length=16),
        ),
    ]
