# Generated by Django 5.2.17 on 2026-10-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('scf', '매출채권'), ('stock_loan', '주식담보'), ('mortgage', '부동산담보'), ('personal_credit', '개인신용')], max_length=20)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('target_amount', models.BigIntegerField()),
                ('raised_amount', models.BigIntegerField(default=0)),
                ('repay_type', models.CharField(choices=[('equal_installment', '원리금균등'), ('equal_principal', '원금균등'), ('bullet', '만기일시')], max_length=20)),
                ('platform_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repay_day', models.PositiveSmallIntegerField(default=25)),
                ('borrower_id', models.CharField(db_index=True, max_length=40)),
                ('borrower_name', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('recruiting', 'Recruiting'), ('recruited', 'Recruited'), ('executed', 'Executed'), ('repaying', 'Repaying'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('loss', 'Loss')], default='draft', max_length=12)),
                ('overview', models.JSONField(default=dict)),
                ('detail', models.JSONField(default=dict)),
                ('notice', models.TextField(blank=True)),
                ('recruit_open_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('refinance_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
        ),
    ]
