# Generated by Django 5.2.17 on 2026-10-10 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        ('products', '0004_product_products_pr_status_041708_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['due_date', 'status'], name='investments_due_dat_81345a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('investment',), name='uniq_reserved_per_investment'),
        ),
    ]
