# Generated by Django 5.2.17 on 2026-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('held', 'Held'), ('failed', 'Failed')], default='received', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
