# Generated by Django 5.2.17 on 2026-10-10 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_balanced_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='depositintent',
            index=models.Index(fields=['user', 'status'], name='ledger_depo_user_id_deb941_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['created_at'], name='ledger_idem_created_879ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_ledg_account_6e7329_idx'),
        ),
        migrations.AddIndex(
            model_name='pointentry',
            index=models.Index(fields=['user', 'kind', 'expires_at'], name='ledger_poin_user_id_4fbe9e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'created_at'], name='ledger_with_user_id_c6cf5b_idx'),
        ),
    ]
