# Generated by Django 5.2.17 on 2026-10-10 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_depositintent_ledger_depo_user_id_deb941_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositintent',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='depositintent',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_id', ''), _negated=True), fields=('transfer_id',), name='deposit_intent_transfer_id_uniq'),
        ),
    ]
