# Generated by Django 5.2.17 on 2026-10-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', '개인대출'), ('business', '기업대출')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('max_limit', models.BigIntegerField(default=0)),
                ('rate_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('term_desc', models.CharField(blank=True, max_length=100)),
                ('repay_method', models.CharField(blank=True, max_length=100)),
                ('features', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('info', models.JSONField(default=dict)),
                ('faqs', models.JSONField(default=list)),
                ('notices', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimitCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('limit', models.BigIntegerField()),
                ('rate_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('biz_type', models.CharField(blank=True, max_length=30)),
                ('biz_no', models.CharField(blank=True, max_length=20)),
                ('amount', models.BigIntegerField()),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='submitted', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
